In [1]:
from ola_models import * 
from ola_RNN import * 

import os, time, copy, math, re, json, pickle, random
import numpy as np
import pandas as pd

import torch, torchvision
import torchvision.models as models
import torchvision.transforms as transforms
import torch.nn as nn
import torch.nn.init as init
import torch.nn.functional as F
import torch.optim as optim

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.ticker as ticker

from functools import partial 

cuda_available = torch.cuda.is_available()
device = torch.device("cuda:0" if cuda_available else "cpu")
print(f'''using device {device}''')

path = !pwd
path = path[0]
print(path)

using device cuda:0
/home/r2/Documents/RNNexp


In [2]:
bs  = 30
sql = 30 
lr  = 0.0005 

sched = combine_scheds([0.15, 0.25, 0.2, 0.4], [sched_cos(0.0005, 0.0008), sched_cos(0.0008, 0.0005),sched_lin(0.0005,0.0005),sched_cos(0.0005,0.00005)]) 
data          = pp_trumpdata(path+"/data/trump/", [0.9,0.95], bs)
data.train_dl = TweetDataLoader(data,data.train.tweets,bs,sql,shuffle=True)
data.valid_dl = TweetDataLoader(data,data.valid.tweets,30,sql,shuffle=False)

model  = cuda(GRU(len(data.decoder), 150))
opt    = optim.RMSprop(model.parameters(), lr, weight_decay=0.0001, momentum=0.9)
learn  = Learner(model, nn.NLLLoss(), opt , data, lr=lr)

In [3]:
cbs    = CallbackHandler([CounterCallback(1000),StatsCallback()])

In [4]:
fit_rnn(1,learn,cbs)

torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18]

tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
t

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]

torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
 

torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [

torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
 

torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [

torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
ten

torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14]])
torch.Size([30])
tensor([[ 0],
        [ 1],
 

torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Si

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14]

torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [

torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8]

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8]

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21]])
torch.Size([30])
tensor([

tensor([], size=(0, 1), dtype=torch.int64)
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        

torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]

torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [

torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
 

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8]

torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [

torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
 

torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [

torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Siz

torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15]])
torch.Size([30])
tensor([[ 0],
 

tensor([[0],
        [1],
        [2],
        [3],
        [4]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3],
        [4]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3],
        [4]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3],
        [4]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3],
        [4]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3],
        [4]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3],
        [4]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3],
        [4]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3],
        [4]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3],
        [4]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3],
        [4]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3],
        [4]])
torch.Size([30])
tens

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18]

torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6]])
torch.Size([30])
te

torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[

torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [

tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
     

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8]

torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16]

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        

torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [

torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [

torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        

tensor([[0],
        [1],
        [2],
        [3],
        [4]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([], size=(0, 1), dtype=torch.int64)
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [1

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8]

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        

torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])
torch.Size([30])
tensor([[0],
        [1],

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]

torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Size([30])
tensor([[0]])
torch.Si

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8]

torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20]])
torch.Size([30])
tensor([[ 0],
        [ 1],
        [ 2],
     

tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1],
        [2]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
        [1]])
torch.Size([30])
tensor([[0],
   

KeyboardInterrupt: 

In [ ]:
plot_list(learn.stats.train_loss[100::], 'train_loss')
plot_list(learn.stats.train_mva_loss[100::], 'moving_average_train_loss')
plot_list(learn.stats.valid_loss, 'valid loss')
plot_list(learn.stats.valid_accu, 'valid accuracy')

In [ ]:
generate_seq(learn.model,learn.data,300)