In [1]:
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"

In [2]:
from ola_models import * 
from ola_RNN import * 

import os, time, copy, math, re, json, pickle, random
import numpy as np
import pandas as pd

import torch, torchvision
import torchvision.models as models
import torchvision.transforms as transforms
import torch.nn as nn
import torch.nn.init as init
import torch.nn.functional as F
import torch.optim as optim

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.ticker as ticker
%matplotlib inline 
import seaborn as sns

from functools import partial 

cuda_available = torch.cuda.is_available()
device = torch.device("cuda:0" if cuda_available else "cpu")
print(f'''using device {device}''')

path = !pwd
path = path[0]
print(path)

using device cuda:0
/home/r2/Documents/RNNexp


In [3]:
%%javascript
IPython.OutputArea.auto_scroll_threshold = 9999;

<IPython.core.display.Javascript object>

In [163]:
a[:,1]

tensor([[2, 2, 2]])

In [212]:
a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
b = a 
c1 = a[0] @ b[0]
c2 = a[1] @ b[0]
c3 = a[2] @ b[0]
# for i in range(a.shape[0]):            
#     w = a[i].t() @ b[0]
print(c1,c2,c3)
print(a.t() @ b[0])

tensor(14) tensor(32) tensor(50)
tensor([30, 36, 42])


In [213]:
a = a.unsqueeze(0)

In [116]:
import torch.nn.functional as F 

In [238]:
a
# print(sum(a,2))

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [244]:
torch.sum(a,1)

tensor([[12, 15, 18]])

tensor([[[ 14.,  32.,  50.],
         [ 32.,  77., 122.],
         [ 50., 122., 194.]]], device='cuda:0', dtype=torch.float64)
tensor([[2.3195e-16, 1.5230e-08, 1.0000e+00],
        [8.1940e-40, 2.8625e-20, 1.0000e+00],
        [2.8946e-63, 5.3802e-32, 1.0000e+00]], device='cuda:0',
       dtype=torch.float64)
tensor(1., device='cuda:0', dtype=torch.float64)
torch.Size([3, 3])
torch.Size([3])
tensor([[2.3195e-16, 8.1940e-40, 2.8946e-63],
        [1.5230e-08, 2.8625e-20, 5.3802e-32],
        [1.0000e+00, 1.0000e+00, 1.0000e+00]], device='cuda:0',
       dtype=torch.float64)
tensor(1., device='cuda:0', dtype=torch.float64)


In [ ]:
class SAttention(nn.Module):
    
    def __init__(self,x_size):        
        super(SAttention,self).__init__()
        self.x_size = s_size
        # output from query should be [x.shape, x.shape]
        # output from query should be the same but this is a problem
        # why? because the linear layers only takes a flattened vector as input.          
        self.Wq = nn.Linear(self.x_size*self.x_size, self.x_size*self.x_size)         
        self.Wk = nn.Linear(self.x_size*self.x_size, self.x_size*self.x_size)
        #         
        self.Wv = nn.Linear(self.x_size)
                        
    def self_attention(self,X):
        q = self.Wq(torch.flatten(X, start_dim=1))
        q = q.reshape(1,self.x_size,self.x_size)
        k = self.Wk(torch.flatten(X, start_dim=1))
        k = k.reshape(1,self.x_size,self.x_size)        

        w_ = torch.bmm(k, q.transpose(1,2))
        w  = F.softmax(w_,dim=2)
        
        v = self.Wv(torch.flatten(X,start_dim=1))
        v = v.reshape(1,self.x_size,self.x_size)
        
        Y = torch.bmm(w,v)
        
    def self_attention_nolearning(selfm,X):
        w_ = torch.bmm(X, X.transpose(1,2))
        w  = F.softmax(w_, dim=2)    
        Y  = torch.bmm(w, X) 
        return Y 
        
        
        